FROM node:22-alpine as builder
WORKDIR /mini_order_admin

COPY package.json  ./

# 安装 pnpm
RUN npm install -g pnpm
RUN pnpm install

COPY . .

RUN pnpm run build

FROM node:22-alpine as runner
WORKDIR /mini_order_admin

COPY --from=builder /mini_order_admin ./

EXPOSE 6688

CMD ["npx", "next", "start", "-p", "6688"]