FROM node:latest
WORKDIR /mini-order-server
COPY package.json ./
COPY ./.env .env
COPY ./prisma prisma

# 安装 pnpm
RUN npm install -g pnpm

RUN pnpm install


RUN npx prisma generate --schema=./prisma/schema.prisma

COPY . .

RUN npm run build

FROM node:latest


COPY --from=0 /mini-order-server/ ./

CMD node dist/src/main.js

EXPOSE 6666
